language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot README.md --allow-dupe --allow-redirect
  - remark -f --no-stdout README.md
  - danger
notifications:
  email: false
