language: node_js
node_js:
  - "node"
install:
  - yarn
  - gem install awesome_bot
  - gem install danger
script:
  - remark -f --no-stdout README.md
  - awesome_bot README.md --allow-dupe --allow-redirect
  - danger
notifications:
  email: false
